config/routes.rb
Blog::Application.routes.draw do
  get '/posts' => 'posts#index', as: 'principal'
  get '/posts/admi' => 'posts#admi' , as: 'admi'   
  get '/posts/new' => 'posts#new'
  get '/posts/report' => 'posts#report'
  get '/posts/:id' => 'posts#edit'
  get '/posts/delete/:id' => 'posts#delete'
  get '/posts/likes/:id' => 'posts#likes'
  get '/posts/show/:id' => 'posts#show'
   get '/posts/dislikes/:id' => 'posts#dislikes'

  post '/posts' => 'posts#create'
  post '/posts/:id' => 'posts#update'
  post '/comments/:id' => 'comments#create'
   root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :text , :presence => true
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title , :presence => true
	validates :text , :presence => true
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	skip_before_filter :verify_authenticity_token

	def create
    if params.has_key?(:post)
    @post.update(params[:post].permit(:texto))
    redirect_to '/posts'
	end
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	skip_before_filter :verify_authenticity_token

	def index
		@posts=Post.all
	end

	def admi
		@posts=Post.all 
	end

	def new
		@posts = Post.new
	end

	def create
		@posts = Post.new
		@posts.title=params[:post][:title]
		@posts.text=params[:post][:text]
		@posts.category=params[:post][:category]
		@posts.save
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.title = params[:post][:title]
		@post.text = params[:post][:text]
		@post.category = params[:post][:category]
	
		
		if @post.save
			redirect_to '/posts'
		else
			render 'edit'
		end	
			
	end

	def report
		@posts = Post.all
	end

	def delete
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to '/posts/admi'
	end

	def likes
		@post= Post.find(params[:id])
		if @post.likes==nil
    		@post.likes=0
    	end
    	@post.likes=@post.likes+1
    	@post.save
    	redirect_to "/posts"
	end

	def dislikes
		@post= Post.find(params[:id])
		if @post.likes==nil
    		@post.likes=0
    	elsif @post.likes>0		
	    	@post.likes=@post.likes-1
    	else
    		@post.likes=0
    	end
    		@post.save
    		redirect_to "/posts"
	end


	def show
		@post= Post.find(params[:id])
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
su post se creo correctamente

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/admi.html.erb
<h1>Pagina Administrativa</h1>
<a href="/posts">Ir a Pagina Principal</a><br>
<a href="/posts/report"> Ver Reporte</a>
<br>
<br>
<a href="/posts/new">NUEVO POST</a>

<% orden = @posts.order('created_at DESC') %>
<% orden.each do |post| %>
	<p>
		<b>Title:</b>
		<%= post.title %>
	</p>
	<p>
		<b>Text:</b>
		<%= post.text %>
	</p>
	<p>
		<b>Category:</b>
		<%= post.category %>
	</p>
	<p>
		<a href="/posts/<%= post.id %>">Editar</a>
		<a href="/posts/delete/<%= post.id %>">Borrar</a>
	</p>
	<hr style="color:#0000FF">
<% end %>





<h2>Busqueda</h2>

<%= form_tag admi_path, :method => 'get' do %>

    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
    <% pal=params[:search] %>

<table style="border:1px solid black;">
	<tr>
		<th style="padding:0px 30px 0px 30px">Title</th>
		<th style="padding:0px 30px 0px 30px">Text</th>
	</tr>

<% @posts.each do |post| %>
 	<% arr= post.text.split.uniq %>
 	<% arr.each do |palabra| %>
 		<% if palabra==pal %>
			<tr>
				<td style="padding:0px 30px 0px 30px"> <%= post.title %> </td>
				<td style="padding:0px 30px 0px 30px"> <%= post.text %> </td>
			</tr>
		<% end %>
	<% end %>
<% end %>
</table>

<% end %>

app/views/posts/create.html.erb
<b>PELICULA CREADA EXITOSAMENTE</b>
<a href="/posts/admi">atras</a>

app/views/posts/edit.html.erb
<h1>EDITAR POST</h1>


<form action="/posts<%= @post.id ? '/'+@post.id.to_s : '' %>" method="post">
	<b>Post Title:</b>
	<input type="text" name="post[title]" value="<%= @post.title %>">
	<br>
	<b>Post Text:</b>
	<input type="text" name="post[text]" value="<%= @post.text %>"> <br>
	<b>Post Category:</b>
	<select name="post[category]" value="<%= @post.category %>">
   		<option value="religion">religion</option>
	   	<option value="pelicula">pelicula</option>
   		<option value="musica">musica</option>
   		<option value="deporte">deporte</option>
 	</select> 
	<input type="submit" name="commit" value="Modificar">
</form>

app/views/posts/index.html.erb
<h1>PAGINA PRINCIPAL</h1>
<a href="/posts/admi">IR A PAGINA ADMINISTRATIVA</a>

<table>
	<tr>
		<th style="padding:0px 30px 0px 30px">Titulo</th>
		<th style="padding:0px 30px 0px 30px">Texto</th>
		<th style="padding:0px 30px 0px 30px">Category</th>
		<th style="padding:0px 30px 0px 30px">Fecha de Creacion</th>
		<th style="padding:0px 30px 0px 30px">Likes</th>
		<th style="padding:0px 30px 0px 30px">Dislikes</th>
	</tr>

	<% orden = @posts.order('created_at DESC') %>
<% orden.each do |post| %>
	<tr>
		<td style="padding:0px 30px 0px 30px"><a href="/posts/show/<%= post.id %> "> <%= post.title %> </a></td>
		<td style="padding:0px 30px 0px 30px"> <%= post.text %> </td>
		<td style="padding:0px 30px 0px 30px"> <%= post.category %> </td>
		<td style="padding:0px 30px 0px 30px"> <%= post.created_at %> </td>
		<td style="padding:0px 30px 0px 30px"> <a href="/posts/likes/<%= post.id %>"> Like </td>
		<td style="padding:0px 30px 0px 30px"> <a href="/posts/dislikes/<%= post.id %>"> Dislike </td>
	</tr>
<% end %>
</table>
<br>
<hr>

 	<%= form_tag principal_path, :method => 'get' do %>
	<b>filtrar por: religion,pelicula,musica o deporte</b>

    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
    <% pal=params[:search] %>

<table style="border:1px solid black;">
	<tr>
		<th style="padding:0px 30px 0px 30px">Title</th>
		<th style="padding:0px 30px 0px 30px">Text</th>
	</tr>

<% @posts.each do |post| %>
 		<% arr= post.category %>
 		<% if arr==pal %>
			<tr>
				<td style="padding:0px 30px 0px 30px"> <%= post.title %> </td>
				<td style="padding:0px 30px 0px 30px"> <%= post.text %> </td>
			</tr>
		<% end %>
	
<% end %>
</table>

<% end %>

app/views/posts/new.html.erb
<H2>Crear Post</H2>
<form action = "/posts" method="post" >
	<b>Post Title:</b>
	<input type="text" name="post[title]"><br>
	<b>Post Text</b>
	<textarea cols="40" rows="5" name="post[text]">	</textarea><br>
	<b>category</b>
	<select name="post[category]">
   		<option value="religion">religion</option>
	   	<option value="pelicula">pelicula</option>
   		<option value="musica">musica</option>
   		<option value="deporte">deporte</option>
 	</select> 
 <br>
 <input type="submit" name="commit" value="Guardar Post">

</form>

app/views/posts/report.html.erb
<h1>Reporte</h1>
<table>
	<tr>
		<th style="padding:0px 30px 0px 30px">Id</th>
		<th style="padding:0px 30px 0px 30px">Titulo</th>
		<th style="padding:0px 30px 0px 30px">Fecha de Creacion</th>
		<th style="padding:0px 30px 0px 30px">Fecha de Modificacion</th>
		<th style="padding:0px 30px 0px 30px">Cantidad de Comentarios</th>
		<th style="padding:0px 30px 0px 30px">Cantidad de likes</th>
		<th style="padding:0px 30px 0px 30px">Cantidad de Palabras</th>
	</tr>

	<% orden = @posts.order('created_at DESC') %>
<% orden.each do |post| %>
	<tr>
		<td style="padding:0px 30px 0px 30px"> <%= post.id %> </td>
		<td style="padding:0px 30px 0px 30px"> <%= post.title %> </a></td>
		<td style="padding:0px 30px 0px 30px"> <%= post.created_at %> </td>
		<td style="padding:0px 30px 0px 30px"> <%= post.updated_at %> </td>
		<td style="padding:0px 30px 0px 30px"> <%= post.comments.length %> </td>
		<td style="padding:0px 30px 0px 30px"> <%= post.likes %></td>
		<td style="padding:0px 30px 0px 30px"> <%= post.text.split.length %> </td>
	</tr>
<% end %>
</table>

app/views/posts/show.html.erb
<b>Post Title:</b>
<%= @post.title %><br>
<b>Post Text:</b>
<%= @post.text %><br>
<b>Post Likes:</b>
<%= @post.likes %><br>
<a href="/posts/likes/<%= @post.id %>">like</a><br>
<br>
<br>

<h2>Add a comment:</h2>
<form action="/comments/<%= @post.id %>" method="post">
	<textarea name="texto"></textarea>
	<input type="submit" value="Agregar Comentario">
</form>

<h2>Comments</h2>
<% orden=@post.comments.order('created_at DESC') %>
<% orden.each do |comment| %>
   <p>
    <strong>Comment:</strong>
    <%= comment.texto %><br>
    <strong>Fecha de creacion:</strong>
    <%= comment.created_at %>
  </p>
<% end %>
 